FROM mercury/icat:4-base
MAINTAINER Colin Nolan <hgi@sanger.ac.uk>

ENV RENCI_URL=ftp://ftp.renci.org

ADD extract-db-settings.sh /tmp/extract-db-settings.sh
ADD install-irods.sh /tmp/install-irods.sh
ADD setup-irods.sh /tmp/setup-irods.sh
ADD responses.txt /tmp/responses.txt